import { ApplicationConfig, provideZoneChangeDetection, importProvidersFrom, isDevMode } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import {
  LucideAngularModule,
  Wallet,
  LayoutDashboard,
  ArrowLeftRight,
  Tags,
  User,
  LogOut,
  Sun,
  Moon,
  Mail,
  Lock,
  UserPlus,
  LogIn,
  MoveRight,
  AlertCircle,
  CheckCircle,
  Plus,
  Pencil,
  Trash2,
  X,
  TrendingUp,
  TrendingDown,
  ArrowsUpFromLine,
  Repeat,
  Target,
  Folder,
  ChevronLeft,
  ChevronRight,
  Download,
  Search,
  Menu,
  BarChart2,
  PieChart,
  RefreshCw,
  Calendar,
  Settings2,
  Sparkles,
  Camera,
  Upload,
  Check
} from 'lucide-angular';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth';
import { provideServiceWorker } from '@angular/service-worker';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(LucideAngularModule.pick({
      Wallet,
      LayoutDashboard,
      ArrowLeftRight,
      Tags,
      User,
      LogOut,
      Sun,
      Moon,
      Mail,
      Lock,
      UserPlus,
      LogIn,
      MoveRight,
      AlertCircle,
      CheckCircle,
      Plus,
      Pencil,
      Trash2,
      X,
      TrendingUp,
      TrendingDown,
      ArrowsUpFromLine,
      Repeat,
      Target,
      Folder,
      ChevronLeft,
      ChevronRight,
      Download,
      Search,
      Menu,
      BarChart2,
      PieChart,
      RefreshCw,
      Calendar,
      Settings2,
      Sparkles,
      Camera,
      Upload,
      Check
    })), provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000'
    })
  ]
};
